name: CI Build

# Cancel older, in-progress CI runs on the same branch/PR
concurrency:
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Linter
        run: >
          DOCKER_BUILDKIT=1 docker build
          --target=linter
          --progress=plain
          .
  
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test and collect coverage
        continue-on-error: true
        run: >
          DOCKER_BUILDKIT=1 docker build
          --target=coverage_export
          --output type=local,dest=coverage
          --build-arg KEY=${{ secrets.KEY }}
          --build-arg SECRET=${{ secrets.SECRET }}
          --build-arg CONDUCTOR_SERVER_URL=${{ secrets.CONDUCTOR_SERVER_URL }}
          .

      - name: Collect coverage file
        run: |
          set -euo pipefail
          mkdir -p coverage/artifacts
          
          # Look for the test-generated coverage report
          report="$(find coverage -type f -name 'coverage.cobertura.xml' | head -n 1 || true)"
          
          if [ -n "$report" ]; then
            echo "Found coverage report at: $report"
            cp "$report" coverage/artifacts/coverage.cobertura.xml
          else
            echo "No coverage report found — creating an empty stub"
            echo '<coverage></coverage>' > coverage/artifacts/coverage.cobertura.xml
          fi
      
      - name: Upload Cobertura artifact
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: cobertura
          path: coverage/artifcats/coverage.cobertura.xml

      - name: Codecov upload
        if: ${{ !env.ACT }}
        uses: codecov/codecov-action@v5
        with:
          files: coverage/artifacts/coverage.cobertura.xml
          flags: unittests