name: CI Build

on: [push, pull_request,workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Linter
        run: >
          DOCKER_BUILDKIT=1 docker build
          --target=linter
          --progress=plain
          .
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: >
          DOCKER_BUILDKIT=1 docker build
          --target=test
          --build-arg KEY=${{ secrets.KEY }}
          --build-arg SECRET=${{ secrets.SECRET }}
          --build-arg CONDUCTOR_SERVER_URL=${{ secrets.CONDUCTOR_SERVER_URL }}
          .
